name: Convert Lexicons to OpenAPI

on:
  push:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout bluesky-social/atproto repository
        uses: actions/checkout@v3
        with:
          repository: bluesky-social/atproto
          path: atproto

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Cache dependencies
        run: deno cache main.ts

      - name: Convert atproto/lexicons to OpenAPI spec
        run: deno task run
